//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMCG.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMCGDBEntities : DbContext
    {
        public FMCGDBEntities()
            : base("name=FMCGDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountGroup> AccountGroups { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankAccountType> BankAccountTypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CreditLimitType> CreditLimitTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<JournalBank> JournalBanks { get; set; }
        public virtual DbSet<JournalCash> JournalCashes { get; set; }
        public virtual DbSet<JournalCheque> JournalCheques { get; set; }
        public virtual DbSet<JournalCustomer> JournalCustomers { get; set; }
        public virtual DbSet<JournalLedger> JournalLedgers { get; set; }
        public virtual DbSet<JournalOnline> JournalOnlines { get; set; }
        public virtual DbSet<JournalStaff> JournalStaffs { get; set; }
        public virtual DbSet<JournalSupplier> JournalSuppliers { get; set; }
        public virtual DbSet<JournalTT> JournalTTs { get; set; }
        public virtual DbSet<Ledger> Ledgers { get; set; }
        public virtual DbSet<LedgerOpening> LedgerOpenings { get; set; }
        public virtual DbSet<LogDetail> LogDetails { get; set; }
        public virtual DbSet<LogDetailType> LogDetailTypes { get; set; }
        public virtual DbSet<LogMaster> LogMasters { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentBank> PaymentBanks { get; set; }
        public virtual DbSet<PaymentCash> PaymentCashes { get; set; }
        public virtual DbSet<PaymentCheque> PaymentCheques { get; set; }
        public virtual DbSet<PaymentCustomer> PaymentCustomers { get; set; }
        public virtual DbSet<PaymentLedger> PaymentLedgers { get; set; }
        public virtual DbSet<PaymentOnline> PaymentOnlines { get; set; }
        public virtual DbSet<PaymentStaff> PaymentStaffs { get; set; }
        public virtual DbSet<PaymentSupplier> PaymentSuppliers { get; set; }
        public virtual DbSet<PaymentTT> PaymentTTs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<PurchaseReturn> PurchaseReturns { get; set; }
        public virtual DbSet<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<ReceiptBank> ReceiptBanks { get; set; }
        public virtual DbSet<ReceiptCash> ReceiptCashes { get; set; }
        public virtual DbSet<ReceiptCheque> ReceiptCheques { get; set; }
        public virtual DbSet<ReceiptCustomer> ReceiptCustomers { get; set; }
        public virtual DbSet<ReceiptLedger> ReceiptLedgers { get; set; }
        public virtual DbSet<ReceiptOnline> ReceiptOnlines { get; set; }
        public virtual DbSet<ReceiptStaff> ReceiptStaffs { get; set; }
        public virtual DbSet<ReceiptSupplier> ReceiptSuppliers { get; set; }
        public virtual DbSet<ReceiptTT> ReceiptTTs { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SalesDetail> SalesDetails { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual DbSet<SalesReturn> SalesReturns { get; set; }
        public virtual DbSet<SalesReturnDetail> SalesReturnDetails { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StockGroup> StockGroups { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<UserTypeDetail> UserTypeDetails { get; set; }
        public virtual DbSet<UserTypeFormDetail> UserTypeFormDetails { get; set; }
    }
}
