//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ledger()
        {
            this.JournalCashes = new HashSet<JournalCash>();
            this.JournalLedgers = new HashSet<JournalLedger>();
            this.PaymentCashes = new HashSet<PaymentCash>();
            this.PaymentLedgers = new HashSet<PaymentLedger>();
            this.ReceiptCashes = new HashSet<ReceiptCash>();
            this.ReceiptLedgers = new HashSet<ReceiptLedger>();
        }
    
        public int Id { get; set; }
        public string LedgerName { get; set; }
        public string PersonIncharge { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> CityId { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string EMailId { get; set; }
        public string GSTNo { get; set; }
        public Nullable<short> CreditLimit { get; set; }
        public Nullable<int> CreditLimitTypeId { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<int> AccountGroupId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual AccountGroup AccountGroup { get; set; }
        public virtual City City { get; set; }
        public virtual CompanyDetail CompanyDetail { get; set; }
        public virtual CreditLimitType CreditLimitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalCash> JournalCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalLedger> JournalLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentCash> PaymentCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentLedger> PaymentLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptCash> ReceiptCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptLedger> ReceiptLedgers { get; set; }
    }
}
