//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptOnline
    {
        public long Id { get; set; }
        public Nullable<long> ReceipttId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string RefNo { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
