//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrderDetail()
        {
            this.SalesDetails = new HashSet<SalesDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SOId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> UOMId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDetail> SalesDetails { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual UOM UOM { get; set; }
    }
}
